import { Item } from "../@types/item";

export let defaultItem = {
    product_id: 0,
    sku: null,
    title: null,
    description: null,
    price: null,
    rrp: null,
    freight_id: null,
    sort: null,
    stock_zero: null,
    product_status: null,
    variation_one_name: null,
    variation_one_value: null,
    variation_two_name: null,
    variation_two_value: null,
    variation_three_name: null,
    variation_three_value: null,
    stock: null,
    brand: null,
    category: null,
    tags: null,
    image: null,
    gtin: null,
    google_category_id: null,
    buy_on_subscription: null,
    afterpay_restricted: null,
    order: null,
    url: null,
} as Item;